name: Deploy Frontend to server

on:
  push:
    branches:
      - main # ou 'master' selon la branche par défaut

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Version stable de Node.js

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # IMPORTANT : On n'envoie que le dossier 'dist' (le résultat compilé de l'application)
          local-dir: ./dist/ 
          # IMPORTANT : Remplacez "./" par le dossier cible sur votre serveur LWS (ex: /sous-domaine-admin/)
          server-dir: ./ 
